### ISSUE TITLE
Audit and improve DB indexing

### ISSUE THREAD

**Issue by nathanielrindlaub** [tnc-ca-geo/animl-api#119]
We're getting email alerts from the prod DB saying:

> Query Targeting: Scanned Objects / Returned has gone above 1000      The ratio of documents scanned to returned exceeded 1000.0 on  animl-cluster-shard-00-01.84ieh.mongodb.net,  which typically suggests that un-indexed queries are being run. To help  identify which query is problematic, we recommend navigating to the Query Profiler tool within Atlas. Read more about the Profiler here. | Query Targeting: Scanned Objects / Returned has gone above 1000 |   | The ratio of documents scanned to returned exceeded 1000.0 on  animl-cluster-shard-00-01.84ieh.mongodb.net,  which typically suggests that un-indexed queries are being run. To help  identify which query is problematic, we recommend navigating to the Query Profiler tool within Atlas.

When I take a look at the MongoDB Atlas Query Profiler and db operation in question, it looks like it's the [`getLabels`](https://github.com/tnc-ca-geo/animl-api/blob/1f1a9fbc1c84f9fea43391ba6d69f95d0ec13cc2/src/api/db/models/Image.js#L68) aggregation that occurs [every time](https://github.com/tnc-ca-geo/animl-api/blob/1f1a9fbc1c84f9fea43391ba6d69f95d0ec13cc2/src/api/resolvers/Fields.js#L20) a `projects` query is requested:

```JSON
{
  "type": "command",
  "ns": "animl-prod.images",
  "command": {
    "aggregate": "images",
    "pipeline": [
      {
        "$match": {
          "projectId": "sci_biosecurity"
        }
      },
      {
        "$unwind": "$objects"
      },
      {
        "$unwind": "$objects.labels"
      },
      {
        "$match": {
          "objects.labels.validation.validated": {
            "$not": {
              "$eq": false
            }
          }
        }
      },
      {
        "$group": {
          "_id": null,
          "uniqueCategories": {
            "$addToSet": "$objects.labels.category"
          }
        }
      }
    ],
    "cursor": {},
}
...
```
That approach to aggregating labels is pretty expensive to begin with (and might be worth re-thinking entirely), but when I look at the existing indexes in prod via MongoDB compass, it looks like we're not doing ourselves any favors by only indexing on the `_id` field. We should definitely be indexing by `projectId` as well - which we are in the dev DB and is defined in the Mongoose `Image` [schema](https://github.com/tnc-ca-geo/animl-api/blob/main/src/api/db/schemas/Image.js). What's odd is that it looks like I added those indexes to the schema over a year ago, so I'm not sure why they didn't get re-indexed on prod?

Additionally, mongo-cursor-pagination [recommends](https://github.com/mixmaxhq/mongo-cursor-pagination#find) that we index every field that might be passed to its `paginatedField` prop. For `Image.queryByFilter()`, it looks like the paginated field options for `Image` querying are basically any column in the image table in the front end that can be sorted, so currently `dateTimeOriginal`, `dateAdded`, and `cameraId`. We've also been using mongo-cursor-pagination elsewhere (for querying Batches and BatchErrors, for example), so it would be worth auditing those and seeing what fields if any should get indexed on their respective collections.

**Comment by nathanielrindlaub** [comment]
Good rules of thumb to follow when planning index strategies here: https://www.mongodb.com/docs/manual/applications/indexes/

**Comment by nathanielrindlaub** [comment]
After reading up on this and the looking at the indexes that MongoDB was recommending through it's "profiler" tab in its UI, I came to the conclusion that I would not have anticipated the indexes it recommended (not even close), so perhaps it's best to create indexes via the UI rather than in code and just follow what the profiler recommends. 

For now let's go with that and see if we run into trouble.

**Comment by jue-henry** [comment]
While investigating indexes and possible optimizations a few potential bugs were found. Adding them here for visibility:

1. Timeout caused when both `reviewed` and `not reviewed` flags are selected:
`"$match": {
          "$or": [
            {
              "objects.locked": false
            },
            {
              "objects": {
                "$size": 0
              }
            },
            {
              "objects": {
                "$not": {
                  "$elemMatch": {
                    "labels": {
                      "$elemMatch": {
                        "$or": [
                          {
                            "validation": null
                          },
                          {
                            "validation.validated": true
                          }
                        ]
                      }
                    }
                  }
                }
              }
            }
          ]
        }
      },
      {
        "$match": {
          "objects.0": {
            "$exists": true
          },
          "objects.locked": {
            "$ne": false
          },
          "objects.labels": {
            "$elemMatch": {
              "$or": [
                {
                  "validation": null
                },
                {
                  "validation.validated": true
                }
              ]
            }
          }
        }
      },
      {
        "$match": {}
      },`
Not exactly a use case that should be supported, since no images should be returned. Should either be handled on frontend to prevent this option from being selected or input check should be done on the backend to prevent this potential timeout. TODO: link issue here

2. When viewing a the home page, we query for images in the project sorted by dateTimeOriginal, and it appears we are also sorting via image._id. This is not explicitly done by us, so we need to investigation is there a potential optimization by removing this secondary sort field. According to [this article](https://www.mongodb.com/docs/manual/reference/bson-type-comparison-order/), date holds precedence to string, so actual sort order isn't affected. Will have to look into if this affects performance. Currently we have an index supporting `projectId, dateTimeOriginal, _id`, this potentially can be simplified to remove _id.

`{
  "type": "command",
  "isFromUserConnection": true,
  "ns": "animl-prod.images",
  "collectionType": "normal",
  "command": {
    "aggregate": "images",
    "pipeline": [
      {
        "$match": {
          "projectId": "island_spotted_skunks"
        }
      },
      {
        "$match": {}
      },
      {
        "$sort": {
          "dateTimeOriginal": -1,
          "_id": -1
        }
      },
      {
        "$limit": 51
      }
    ],`

**Comment by jue-henry** [comment]
Did some cleanup of indexes based on common query requests. Will continue to monitor the performance advisor and for alerts. Opened #161 in order to reduce index size and to more easily query for reviewed/not-reviewed images. Will also update indexes to use this field once the back-end has been updated with this field. In the meantime, created indexes to use `objects.locked` in order to better handle performance.

**Comment by nathanielrindlaub** [comment]
@jue-henry, do we want to close this out in favor of some of the other related DB-optimization issues we have? Or is it worth keeping it open? Up to you.
