### ISSUE TITLE
Bulk Ingestion

### ISSUE THREAD

**Issue by ingalls** [tnc-ca-geo/animl-api#82]
### Context

We've completed our initial testing with bulk ingestion of images through the current sagemaker serverless function approach and
initial numbers strongly support that this is a solid approach to handling larger bulk ingestion events.

This ticket will serve as an initial stub to track next actions and subsequent progress.

### Actions

1. The current major bottleneck in the last run was the actual upload of the images. Uploading from a an average non-gigabit network can be slow and is exacerbated by thousands of individual requests. Since most users will not have credentials & experience necessary to perform an upload via the AWS S3 cli, we should support the upload of a Zip File to the S3 Bucket that could come from the underlying API or a direct CLI call.
  - [ ] Accept .zips in ingest bucket and modify current animl-ingest to detect zips and shunt them to a seperate unzipper SQS Queue
  - [ ] Add an Unzipper SQS Queue  
  - [ ] Configure Unzipper SQS Queue to fire an AWS Batch Task with a configurable disk size to perform the unzip operation and upload individual images to S3
  - [ ] Brainstorm how we should "mark" an ingest as a batch job - IE: batch unzipper creates a database entry for the images and prefixed them into an S3 folder that the ingest lambda can identify and queue
  
### Future Actions / Brainstorming
- Unzipper Queue would dynamically create SQS Queue on a per/batch basis to track progress on a particular batch
- Steal ML-Enabler SQS Monitoring and Automatic Deletion code to monitor a batch and tear down infrastructure after a batch has been completed via CloudWatch Alarms & a lambda
- Add Database Definitions to store information about a batch run (total images, SQS Queue ID, Start Time, etc)
- Update API/UI to be able to read batch state and display batch state to user
- Update API/UI to be able to upload a zip to initiate a batch queue

cc/ @rbavery @nathanielrindlaub

**Comment by rbavery** [comment]
Meeting notes:
Two things to decide:
1. how we accept zip, what frontend and who works on it (Natty or us)
2. how we batch process zip. Nick will work on this first if we have remaining hours, and we'll scope out the rest.

Moving animl to ECS instead of serverless lambdas. Decision - make do with t3 nano instance. get the app off the ground and working. @ingalls - moving express to endpoints not difficult. tiny server to handle uploads, then we refactor to ecs if needed if it becomes a problem. cc @geohacker

**Comment by geohacker** [comment]
This sounds great @ingalls @rbavery! Thank you for documenting. I'm encouraged to hear that we can use more or less the same infrastructure for scaling.

>  moving express to endpoints not difficult. tiny server to handle uploads, then we refactor to ecs if needed if it becomes a problem

@ingalls wouldn't it be better to move to ECS as you move to express?  I worry about Lambda at this frequency.

**Comment by geohacker** [comment]
@ingalls @nathanielrindlaub do you see any upgrades to MongoDB necessary at this point?

**Comment by nathanielrindlaub** [comment]
@geohacker - re. MongoDB, our current DB set up seemed to do OK on the stress test, but I'm currently upgrading us to a dedicated M10 MongoDB Atlas cluster because we have run into some unrelated feature limitations that the free tier does not support (see #81). I've spun up the cluster and am doing some data transfer and testing on it today.
